### ISSUE TITLE
Cannot find module rox-node

### ISSUE THREAD

**Issue by cyrus-za** [g-guirado/rox-ssr-multi-entrypoints#35]
Running into a error when I deploy the nextjs app to vercel. 

```
ERROR	Uncaught Exception 	{"errorType":"Runtime.ImportModuleError","errorMessage":"Error: Cannot find module 'rox-node'\nRequire stack:\n- /var/task/node_modules/rox-ssr/dist/es6/utils.js\n- /var/task/node_modules/rox-ssr/dist/es6/index.js\n- /var/task/node_modules/rox-ssr-multi-entrypoints/dist/es6/index.js\n- /var/task/.next/serverless/pages/logged-in.js\n- /var/task/now__launcher.js\n- /var/runtime/UserFunction.js\n- /var/runtime/index.js","stack":["Runtime.ImportModuleError: Error: Cannot find module 'rox-node'","Require stack:","- /var/task/node_modules/rox-ssr/dist/es6/utils.js","- /var/task/node_modules/rox-ssr/dist/es6/index.js","- /var/task/node_modules/rox-ssr-multi-entrypoints/dist/es6/index.js","- /var/task/.next/serverless/pages/logged-in.js","- /var/task/now__launcher.js","- /var/runtime/UserFunction.js","- /var/runtime/index.js","    at _loadUserApp (/var/runtime/UserFunction.js:100:13)","    at Object.module.exports.load (/var/runtime/UserFunction.js:140:17)","    at Object.<anonymous> (/var/runtime/index.js:43:30)","    at Module._compile (internal/modules/cjs/loader.js:1133:30)","    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)","    at Module.load (internal/modules/cjs/loader.js:977:32)","    at Function.Module._load (internal/modules/cjs/loader.js:877:14)","    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)","    at internal/main/run_main_module.js:18:47"]}Unknown application error occurredRuntime.ImportModuleError
```

Rolout config:
```ts
import { getOr } from 'lodash/fp'
import React, { useEffect } from 'react'
import { Rox, Flag } from 'rox-ssr-multi-entrypoints'
import { ROX_KEY } from '~/src/config/env'

import { useLocalStore } from '../common/localStore'

const flagConfig = {
  // REGISTER ALL FLAGS HERE
  enableNewShifts: new Flag(false),
  processFilter: new Flag(false),
  processStepFilter: new Flag(false),
  enableStepTemplateCategories: new Flag(false),
}
const FlagContext = React.createContext(flagConfig)

const useRollout = () => {
  const flags = React.useContext(FlagContext)
  const [profile] = useLocalStore('profile', {})
  const setProperty = (name: string, value: string) => {
    Rox.setCustomStringProperty(name, value)
  }

  useEffect(() => {
    setProperty('profileEmail', getOr('', 'email')(profile))
  }, [])

  return { flags, setProperty }
}

Rox.register('', flagConfig)
Rox.setup(ROX_KEY, {
  freeze: 'none',
} as any)

export { useRollout, flagConfig, FlagContext }

```

**Comment by g-guirado** [comment]
Not sure how to help here. rox-ssr-multi-entrypoints depends on rox-ssr, and rox-ssr depends on rox-node.

I'm using rox-ssr-multi-entrypoints on a Nextjs project too (although, not serverless) without issue.
```
$ yarn why rox-node
yarn why v1.22.4
[1/4] 🤔  Why do we have the module "rox-node"...?
[2/4] 🚚  Initialising dependency graph...
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
=> Found "rox-node@4.9.6"
info Reasons this module exists
   - "rox-ssr-multi-entrypoints#rox-ssr" depends on it
   - Hoisted from "rox-ssr-multi-entrypoints#rox-ssr#rox-node"
info Disk size without dependencies: "424KB"
info Disk size with unique dependencies: "424KB"
info Disk size with transitive dependencies: "424KB"
info Number of shared dependencies: 0
✨  Done in 0.95s.
```

**Comment by g-guirado** [comment]
@cyrus-za rox-ssr does a dynamic import of rox-node and webpack/nextjs is probably unable to detect it and thus doesn't bundle rox-ssr in your final app.
I'm hoping there is way to force bundle a module but I've no experience with Next.js serverless myself.

**Comment by cyrus-za** [comment]
Thanks @g-guirado for the fast response.

My experience is also fairly limited with it. I figured it's something like that or not installing the modules directly. I tried installing `rox-node` on root, but same issue.

I logged a issue with nextjs [here](https://github.com/vercel/next.js/issues/13736)

**Comment by cyrus-za** [comment]
@g-guirado please see the response from nextjs [here](https://github.com/vercel/next.js/issues/13736#issuecomment-638868578)

**Comment by cyrus-za** [comment]
@g-guirado seeing as you work for cloudbees, is there a way you can find out A) why roxjs is no longer public on github and B) if they can update `rox-ssr` to use `require()` instead of `eval()` as webpack seems to not bundle it when it does not detect the `require()`

**Comment by g-guirado** [comment]
For A), I'm not sure it's ever been open source. I don't expect it to be open source soon; at least not in the sam timeline I'd like to fix this issue.
B) Will find a way to fix rox-ssr, hopefully soon.

**Comment by g-guirado** [comment]
@cyrus-za rox-ssr has been updated (v 4.9.7) and I've published a new rox-ssr-multi-entrypoints v. 0.1.14. Could you try again?

**Comment by g-guirado** [comment]
Closing. Please reopen if you still see the issue.
